name: Setup Java & Gradle
description: Setup Java & Gradle
runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
