name: SpectatorTheater
version: '${version}'
main: com.github.sigureruri.spectatortheater.SpectatorTheater
authors: [ SigureRuri ]
commands:
  spectatortheater:
    usage: /<command> [start|end]
    aliases: [spectator]
    permission: spectatortheater.command.spectatortheater
    permission-message: "You don't have permission to execute this command."
permissions:
  spectatortheater.command.spectatortheater:
    default: op
  spectatortheater.command.spectatortheater.start:
    default: op
  spectatortheater.command.spectatortheater.end:
    default: op