name: SpectatorTheater
version: '${version}'
main: com.github.sigureruri.spectatortheater.SpectatorTheater
authors: [ SigureRuri ]
commands:
  spectatortheater:
    usage: /<command> [start|end|list]
    aliases: [spectator]
permissions:
  spectatortheater.start:
    default: op
  spectatortheater.end:
    default: op
  spectatortheater.list:
    default: op