name: CD
on:
  push:
    branches:
      - main
jobs:
  bump:
    name: Bump version
    runs-on: ubuntu-latest
    outputs:
      new-ver: ${{ steps.output-ver.outputs.new-ver }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java & Gradle
        uses: ./.github/actions/setup
      - name: Bump version
        uses: gradle/gradle-build-action@v2
        with:
          arguments: releaseVersion
      - name: Push changes
        run: git push --follow-tags
      - name: Set output of new ver
        id: output-ver
        run: |
          VER=$(git describe --tags --abbrev=0)
          echo "$VER"
          echo "{new-ver}={$VER}" >> $GITHUB_OUTPUT
  build:
    name: Build
    needs:
      - bump
    uses: ./.github/workflows/ci.yml
  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - bump
      - build
    steps:
      - uses: actions/checkout@v3
      - name: Fetch and checkout again
        run: |
          git fetch --prune --unshallow
          git checkout $(git describe --tags --abbrev=0)
      - name: Download jar
        uses: actions/download-artifact@v3
        with:
          name: jar
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.bump.outputs.new-ver  }}
          files: ./*.jar
