name: CI
on:
  pull_request:
    branches:
      - main
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/output-latest-tag
        id: latest-tag
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew shadowJar
      - uses: actions/upload-artifact@v4
        with:
          name: jar
          path: build/libs/*.jar
