name: CI
on:
  pull_request:
    branches:
      - main
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch again
        run: git fetch --prune --unshallow
      - name: Setup Java & Gradle
        uses: ./.github/actions/setup
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: shadowJar
      - uses: actions/upload-artifact@v3
        with:
          name: jar
          path: build/libs/*.jar
