name: CI
on:
  pull_request:
    branches:
      - main
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/output-latest-tag
        id: latest-tag
      - name: Checkout a latest tag
        if: ${{ github.ref == 'refs/heads/main' }}
        run: git checkout ${{ steps.latest-tag.outputs.latest-tag }}
      - name: Setup Java & Gradle
        uses: ./.github/actions/setup
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.11.1
        with:
          arguments: shadowJar
      - uses: actions/upload-artifact@v3
        with:
          name: jar
          path: build/libs/*.jar
